### ISSUE TITLE
I am getting an empty image

### ISSUE THREAD

**Issue by jcorpusg** [mgp25/Chat-API#1577]
I have tried with many numbers to get all images that they send, but almost half of everyone I get an empty image. This is my code:

```php
function onGetImage( $mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption ) {

$remitente = substr($from,0,13);
echo "Se recibio una imagen del numero $remitente.\n\n";
$fechaImagen = date('Ymd_H-i-s');
file_put_contents(dirname(__FILE__).'\\'.Constants::PICTURES_FOLDER.'\\Imagen'.$fechaImagen.'.jpg',$file);
	echo 'Imagen guardada en '.dirname(__FILE__).'\\'.Constants::PICTURES_FOLDER.'\\Imagen'.$fechaImagen.'.jpg';
}
```

I was getting 0 byte images, and I don't know what I am wrong.

Will it be necesary add some timeout in order to wait the file saves correctly?

**Comment by wragnar** [comment]
With the encryption options, when some number (i think it depens if the source has encryption activated or not) send you an image, arrives twice.

So the best thing to do is add a 4 digit random number in the name of the file, because what is happening to you is that first arrives the correct image an then an empy one so the second overwrites the first, whit a random digits in the filename, you will get two images from the same $fechaimagen one with the image and another empty.
