### ISSUE TITLE
Banned for using API

### ISSUE THREAD

**Issue by mgellan** [mgp25/Chat-API#1642]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.

### Error
I just started playing with the API today, used WART to get my password etc. Wrote a little app that sends a whatsapp to my account (and a couple of friends when it wasn't working.) I guess the act of getting a password on the invalidated my phone API, I was locked out for three hours, got back in, ran my program again and discovered soon after I was banned from whatsapp. No time limit so not sure it's a temp ban. I've sent a note to support to find out whats going on. Thought I should post something...

### Debug log
Post your debug log below:

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
@mgellan i recommend you using `registerTool.php` which is a CLI script provided in the `example` folder. Yes, that is also explained in the wiki, you can only use your account in one device at a time, other possibility would be to extract the password from the device, but the session is unique, if you try logging in other device, you will be kicked off your session.

When you are using the API, make sure you have a right flow because if not, WhatsApp can block you, there is a flow example in the wiki.

Regards
