### ISSUE TITLE
Bad Mac, infinite retry related to #1734

### ISSUE THREAD

**Issue by JJF2** [mgp25/Chat-API#1751]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

Since a couple of days I'm experiencing frequent disconnection.

I have a lot of
`Decrypted Message: Bad Mac!
No valid sessions - ...Whatsapp\src\libaxolotl-php\SessionCipher.php 
`

Deleting axolotl.db temporary solve the problem but it last only for few messages.

I have two number running over a year. now both have the same issue.

**Waiting for the new release is it there something to mitigate the issue?**

**Comment by mgp25** [comment]
There is some workaround, but i would recommend to wait for the next release

**Comment by timbersoen** [comment]
Hi JJF2,
Try to send a message from your API to the number which caused the bad mac. This creates a new session for that number. Next incoming message from that number wil work.
Regards.

**Comment by Entreprenerd** [comment]
When is next release coming?

**Comment by 0xTryCatch** [comment]
Days, weeks or months

**Comment by Sdlion** [comment]
It seems that on onDisconnect event executing `DELETE FROM sessions` on axolotl db eases the problem. For those who doesn't know about this db is on `vendor/whatsapp/chat-api/src/wadata/axolotl-CONTACTNUM.db`.

I couldn't find a way to programmatically send back a messsage to the troubled contact with "Bad Mac!" message as @timbersoen suggested since msg decryption errors won't trigger an onError event.

I've also tried unlinking axolotl database but that would result on a `SQLSTATE[HY000]: General error: 8 attempt to write a readonly database`
And deleting everything on axolotl tables would result on a `SQLSTATE[HY000]: General error: 17 database schema has changed` error too.
