### ISSUE TITLE
New numbers get blocked!!

### ISSUE THREAD

**Issue by elchobo5** [mgp25/Chat-API#1832]
Hi,

we're seeing that all numbers registered after April 4th are blocked, but if we use code and password get before that date all works fine.

Please, is there an issue with registration with new WA protocol?

### Error
sytem shut down

**Comment by 0xTryCatch** [comment]
How many numbers?

**Comment by david-perez** [comment]
Yup, this is true. I've tried registering 3 numbers in late March / April, and **all** of them were blocked within 24h, one of them without even logging in. They're banning numbers that are registering with the old client configuration.

I've given up opening new issues, since [you close all of them](https://github.com/mgp25/Chat-API/issues/1769).

**Comment by 0xTryCatch** [comment]
We close issues of spammers. Registering many numbers is not personal use.

**Comment by david-perez** [comment]
I do not do spamming. It's for personal use.
But if I'm unable to even log in what is the point.

**Comment by 0xTryCatch** [comment]
We may be wrong but there's too much spam out there we need to get rid of before we move on (if we even move on)

**Comment by elchobo5** [comment]
We have used 27 different numbers, registered in WA since April 7th.These number were running in different servers. With many numbers, after the registration, no messages were send or received, but WA sent a "system shutdown" message after a while. After that, a "not authorized" message is received when we attempt to re-login.

**Comment by david-perez** [comment]
Man, 27 numbers running concurrently... well that's certainly not for personal use, I suspect. @elchobo5 Care to explain your use case?

**Comment by Flowst** [comment]
My number got blocked too. Lasting for 12h since this morning. And yes everything is up-to-date and no i only use on number after another so it's no commercial or spam.

**Comment by elchobo5** [comment]
We are using very few numbers, But when one of them was changed to "not authorized" we have registered another one. So, in total we have registered 27 numbers during these last days. There were not running concurrently.

**Comment by david-perez** [comment]
In any case, I don't care what other users' use cases are.

The fact still remains that the inability to register and use new numbers with this API **is** an issue.
If devs are witholding support in order to cut down on the number of spammers, say it upfront.
If you really don't know how to resolve this issue right now, say it upfront.

But please, at least admit that the issue exists.
It's really infuriating to see how devs turn a blind eye to this problem by blaming it on the users.

**Comment by mgp25** [comment]
@david-perez issue doesnt exists, people doing thing the dont know is what really happens.

And yeah, im not going to publish new release until 1.6 dies and passes some time.

And by the way, its user issue, if you dont understand how it works you wont do anything and mostly to be blocked
