### ISSUE TITLE
Number blocked

### ISSUE THREAD

**Issue by pereira49** [mgp25/Chat-API#1867]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ X ] You are using PHP > 5.6
- [ x ] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ x ] You have checked if someone has already asked the same issue you have.
- [ x ] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ x ] Is not a programming question.
- [ x ] You are using latest Chat API code.

### Error
Post your error below:
I registered a number today, after few hours the number was blocked. I received a message and answered. What i'm doing wrong?

### Debug log
Post your debug log below:
[log_whats.txt](https://github.com/mgp25/Chat-API/files/237620/log_whats.txt)

```xml
YOUR DEBUG LOG HERE
```

**Comment by mgp25** [comment]
Lots of presence, bad flow coded, etc. Make sure is synced both ways... there are a lot of answered issues similar to this one.

Regards

**Comment by samuelg78** [comment]
@mgp25 So how long can we stay online in a day? Please give an estimation, maybe 50/50%? Please let me know where can i find the new flow logic.

**Comment by pereira49** [comment]
@mgp25 i send presence every 30 seconds, just to keep online. I synced with number (i received a message and after synced with this number). I have another number with this same flow, but this was registered a 40 days ago and was not blocked. I have readed all isues about blocked, but it's strange because another number is fine, but this was registered today no. 

It seems to have something new in whatsapp, after the latest updates that are blocking new registration as other issues here.

**Comment by yniwly43** [comment]
Not sure you need to send presence every 30 seconds.

And yes, if tihs is a new number, maybe it is under "new rules".. and you get banned.
This might change in the future, if the developers here find a solution (which seems doubtful).. and it might not. We don't know.

**Comment by softcode2** [comment]
I  agree with @pereira49 & @yniwly43

The problem not by our side or coded. 
It's new rules of whatsapp just for new numbers .

Yesterday I was registered new number then just use it for sent 5 msg to my number.

Today I got banned by whatsapp  for my number with Server IP .

All was working before with my old number and same code I am using 

I am sure 100% it's not our code problem.  Because I already use same code from more than 5 months. 


Any sulotion for this or this API reached to ( The END)


And thanks for @mgp25 for this greats works .

Regards

**Comment by yniwly43** [comment]
It seems like this API has reached its useful lifetime end.. sad :(

**Comment by mgp25** [comment]
its always because of the code and the activity you do, so since this is diplicate and i have told already whats is wrong in that debug log : lots of presences without any reason this issue is closed.

What here happens is that people dont know what they are even doing

_sigh.._

**Comment by yniwly43** [comment]
@mgp25 , thing is - this happens to many, many people, in many different scenarios.

I got banned several times without sending even 1 message:

* Registered a REAL number with the real application
* Used it, sent a message normally. All is well.
* Registered again using Yowsup.
* Login using Yowsup.
* Presence: available.
* Presence: subscribe to some numbers.
* Wait for incoming messages, mark them as Read when they arrive. [We receive commands and control a Linux server from a far using that]
* No outgoing messages at all.

This happened with several different numbers. (Numbers cost 2$ here, so I tried several to try and understand it.)

**Comment by mgp25** [comment]
Is not my problem if people do things bad, im using the same number for 2 years, and i dont think thats a coincidence. As i always tell, this is for personal usage only, other activities will end in a block.

I can chat with all my friends and family, i use it to control and automate sensors at my house, everything works well, i dont think this is a coincidence

**Comment by yniwly43** [comment]
@mgp25 completely true.
but once again, look at my flow.. is it strange or bad things? It is purely personal use..
also, look at Yappari.. a IM application for Maemo. It was blocked also. Purely personal use..

**Comment by eaba** [comment]
Hello @mgp25, I feel like a mother watching her child(idea) die and feeling why you impregnated me in the first place. That said
It is not a coincidence that you have your number working for two years because two years ago you discovered/understood how the blocking works! I believe you are using a slightly modified version of this api so that is why you cant get blocked. to be more specific, you are definitely using a different token than the rest of us!

I cant blame you for that, however, please I need your help and I want to learn from you and know what you know. Where i come from it is said only the thief that runs from the police. My intentions for using this api are genuine and no spam meant and I am will to sign MoU!

When you created this API, you created a womb for ideas to be conceived, please dont let great ideas get aborted or die!

**Comment by 0xTryCatch** [comment]
@eaba You could not be more wrong!
