### ISSUE TITLE
Blocked. Related to #1872

### ISSUE THREAD

**Issue by gleichnerv** [mgp25/Chat-API#1873]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Same as #1872.
My number was running almost everyday for over a year.
This morning I made the login as usual, read some messages and without any activity, at 10:38 I received "system shutdown".

I'm seeing too many bans in these days, I don't think all these are users mistakes. More likely wa started a cleanup....

**Comment by mgp25** [comment]
Without debug log = invalid issue

**Comment by gleichnerv** [comment]
>Without debug log = invalid issue

Log is useless in this case! Normal flow for over a year then:

```
rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>
```

Many many many people in these days are reporting blocking on either new and long time numbers. This can't be a coincidence.

This is not an api issue but maybe an outdated protocol. Or Wa guys become smarter than us.

I think you should admin that a problem exist and stop blaming user for their behaviour, their code and so on.

also many posts telling the same story on #1872 are disappeared...why? I don't think censorship is a good think

**Comment by mgp25** [comment]
@gleichnerv im a little tired you know?

It works perfectly, just used as all explanations given.

WA 1.6 which is the protocol that is using the current Chat API version in github works and its not outdated since other platform still use it, so stop blaming on the protocol.

And really users dont help in anything, the whole work of this is done by 3 persons.

I think you should research for yourself and see what going wrong in your code, since you havent researched WhatsApp i think you dont know whats happening and therefore your issues, and i admit people is using this API like shit because they simply dont know how to use it and use it according the EULA i posted in github.

And if you think this kind of comments:

`+1 i have this issue`

`yes it happens to me too`

`help im idiot`

helps in something, they are not, just spam comments, trash, it really makes harder to manage to repository and harder to people so find the answer, so i remove comment that doesnt aport any information or give wrong information about the related issue.

damn this people

**Comment by gleichnerv** [comment]
>so stop blaming on the protocol.

Ok, it was just an hypothesis. Good to know that is wrong.

>the whole work of this is done by 3 persons.

Belive me, I really admire the team and I'll never end thanking for all the terrific work you've done.

But, (please get this as a constructive criticism) sometimes seems that you shrug off some issues blaming users code, users behave etc and after a while exits a fix.

>I think you should research for yourself and see what going wrong in your code

This is the point. I don't pretend that my code is error-free but it worked every day for a year. No recent changes nor usage modification.
I thought that maybe they are blacklisting IP ranges from major hosting companies, datacenter etc.

>And if you think this kind of comments:
>+1 i have this issue
>yes it happens to me too
>help im idiot

>helps in something, they are not, just spam comments, trash, it really makes harder  to manage to repository and harder to people so find the answer, so i remove  comment that doesnt aport any information or give wrong information about the  related issue.

I agree that most of that comments are stupid and useless but sometimes that indicates that something is happening.
In any case I don't like censors.

**Comment by schoerg** [comment]
@gleichnerv nobody is censoring anything.
