### ISSUE TITLE
@mgp25 you've been blocked?

### ISSUE THREAD

**Issue by gleichnerv** [mgp25/Chat-API#1964]
In your Instagram-API repository you wrote 

*"Unfortunately WhatsApp blocked me (Yes, WhatsApp, sigh...) and my UUID, so they blocked me the use of any account on my mobile phone. There was a way to bypass it, but it was not a final solution, so I decided to do this."*

So, when you wrote:
*"its always because of the code and the activity you do" *
or 
*"Is not my problem if people do things bad, im using the same number for 2 years, and i dont think thats a coincidence"*
or
*"I think you should research for yourself and see what going wrong in your code"*

You were just blaming users for free!

I think the conclusion is that ChatApi is dead.

**Comment by mgp25** [comment]
@gleichnerv hello my friend,

since you have problems with reading comprehension, im going to explain it to your more clear. If you read carefully, it says: blocked me the use of any account **on my mobile phone**

I think that you should read and be sure what you are posting, otherwise you will look dumb posting these kinds of things.

Have a lovely night.

**Comment by SudoHenk** [comment]
I wondered in the beginning why Issues were closed so fast in this repo, but now I understand. Most "devs" aka commercial abusers are assholes and retarded at the same time.

**Comment by breakerh** [comment]
@SudoHenk lol what is your problem? Don't like the repo or the developer. Don't use the code and move on!
damn..
