### ISSUE TITLE
How to use api and keep using on my phone, both with the same code?

### ISSUE THREAD

**Issue by RempelOliveira** [mgp25/Chat-API#2067]
It's possible?

**Comment by MoudiZd** [comment]
No is not possible, any connection using this code will authenticate your phone number with a specific token that will be saved within your wadata folder.

A phonenumber cannot be authenticated with more than password or token and by the way more than device

Web whatsapp is possible because the session you log with using web whatsapp is the same that is used with your phone , till that you notice that when your phone is not connected you cannot use the web whatsapp , because as i told you that the we used same phone session.

Regards !

**Comment by RempelOliveira** [comment]
Too bad. For an application would need a cell phone number only for that.

I saw on the internet that you can redeem the password used in the cell phone, with her would not be possible?
