### ISSUE TITLE
Plese don't close this issue - please let the people read first - Work together!

### ISSUE THREAD

**Issue by fcosystems** [mgp25/Chat-API#2078]
someone has been successful for at least one week in these last days ?

A serious proposal to create an open template of how to use the library mimicking the human thread behavior and following the work flow and  **Working together.**

I have some function to share.

what do you think about ?

(sorry for my english I'm using google)

**Comment by davidsantanacosta** [comment]
So for this purpose I am starting a community so that we can discuss about these issues on the behavior and blocking numbers with experimental purpose. on Slack

If anyone is interested please send me your e-mail to me at this address.

davidcosta@csthost.com.br
----------- PT
Então para esse propósito estou iniciando uma comunidade para que nós possa discutir sobre esses assuntos sobre o comportamento e bloqueio dos números com propósito experimental. on Slack

Se alguem se interessar por favor me mandem seus emails para mim neste endereço.

davidcosta@csthost.com.br
