### ISSUE TITLE
Poll Message not working.

### ISSUE THREAD

**Issue by abhishekdeshkar** [mgp25/Chat-API#2154]
Hello,

I know the support is not available but still posting this. Poll Message function is not working I guess.

```
<?php

require_once('src/whatsprot.class.php');


$username = "xxx";
$nickname = "xxx";
$password = "xxx"; // The one we got registering the number
$debug = true;

$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!


$w->pollMessage();

$w->disconnect();
```

**Comment by mgp25** [comment]
The code is outdated. And anyway you are disconnecting too soon

**Comment by abhishekdeshkar** [comment]
@mgp25 : Thanks! I'm using it on Raspberry pi for home automation. Can I use it ?

**Comment by Dev-Aryan** [comment]
@mgp25 
Hello brother,
I know you have closed the support for this API but it was when this API was working perfectly but, currently this API is dead now. We know there are many users using this API for spamming but there are also many people who are using it for good and/or interesting purpose. So, can you please tell us that when will you or will you update this code with the new one so that we can stop checking this API every day for updates.

(I request you to release the new code ASAP because i also loved using this API)


Regards
Aryan Chauhan
