### ISSUE TITLE
Put end-of-support message at top of README

### ISSUE THREAD

**Issue by mikelambert** [mgp25/Chat-API#2213]
There is no mention in your README on the github mainpage about the end-of-support.

But there is still a request for donations to help support the project, which I find very misleading. :(

I suspect this also contributes to why you continue to see a plethora of new issues and pull requests coming in. Which probably confuses everyone. :(

Also, I'm surprised you've basically shut down development *entirely*, as opposed to potentially handing this off to others who might be interested in maintaining it through forks, adding additional collaborators, etc. (ie, the approach done by almost all other github projects whose original owner no longer wishes to maintain them, despite having a buzzing community). Instead you seem to be actively spending time to shut down bugs and pull requests...which seems quite bizarre to me.

Perhaps you've been threatened/warned/asked/paid by FB/whatsapp to avoid further development, and not to mention that they've told you to do this. That explanation (if true) would at least make some sense as to why it wasn't handed off...

Alas, I suspect you will immediately close this issue too, but at least wanted to put this request on the record to you. :) Good luck to your future projects you choose to work on!

**Comment by mikelambert** [comment]
Likewise, in addition to the README, the top post in https://github.com/mgp25/Chat-API/wiki/WhatsApp-incoming-updates doesn't relate to end-of-support (you have to scroll down past the fold to even see that)

**Comment by mgp25** [comment]
1. None of the pull requests makes sense in any of the ways.
2. All opened issues are already answered, yes seriously, all of them has been previously answered. People often forgets that there is a search tab at the top of the page.
3. There is enough info so people can continue researching, but still lazy and want developers to do the work for them
4. If i stopped is because im sick of seeing spammers using my API without any type of control
5. Las update in `WhatsApp-incoming-updates` dates from August 2016
6. When you try to open an issue, the only thing you see is: `End of support`

Ill probably add that to the readme or detele the repo

Thanks for your recommendation.

Regards
