### ISSUE TITLE
Stream:Error , Please advise !

### ISSUE THREAD

**Issue by 0xFlint** [mgp25/Chat-API#2221]
Hi,

In the last week i've been getting the following errors:
`<stream:error> <ack id=PSAS1487100006><ack><stream:error>`

i'm getting the following before hand:

`<notification from=status@broadcast type=psa id=PSAS1487100006 participant=0@s.whatsapp.net mode=status notify=WhatsApp t=1507820228> <message type=media id=PSAS1487100001 order=1487100001> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100002 order=1487100002> <media type=msg mediatype=gif><media><message> <message type=media id=PSAS1487100003 order=1487100003> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100004 order=1487100004> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100005 order=1487100005> <media type=msg mediatype=image><media><message> <message type=media id=PSAS1487100006 order=1487100006> <media type=msg mediatype=image><media><message><notification>`

And i see the following reply

```
<receipt to=status@broadcast id=PSAS1487100001 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100002 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100003 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100004 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100005 participant=0@s.whatsapp.net><receipt>
<receipt to=status@broadcast id=PSAS1487100006 participant=0@s.whatsapp.net><receipt>
```

I also tried sending ack for:
`"<ack id=PSAS1487100006><ack>"`

and also tried to send double time the receipts again.

Any idea? Please.

@tgalal  @mgp25  @CODeRUS  - Can you maybe assist with your vast knowledge?

**Comment by gekkedev** [comment]
[Read this](https://github.com/mgp25/Chat-API/issues/2116)

**Comment by 0xFlint** [comment]
I know about end of support for the library, but wanted to get advice from the experts ( and the community)

**Comment by gekkedev** [comment]
So, did you read that the further development continues privately? The last updates were over a year ago.

**Comment by 0xFlint** [comment]
I did. And still this is my way to reach out to the active developers, since i don't know any other except me.

Important notice- this issue is even with Vanilla whatsapp (apk from store).

**Comment by 0xFlint** [comment]
Seriously? not even sending an hint about what ack is missing?

**Comment by acalatrava** [comment]
I found the same problem but the funny thing is that I’m not using Chat-API but the standard iOS app on a jailbroken iPhone and I found the same problem which is weird since I don’t mess with the protocol at all. In fact I just used a new number, register it and it start to happen. I know this is not the channel to discuss this since there is no support of the project, but I’ve been  la few days messing with this and I’m unable to find a solution yet. I was able to extend the connection time to 5 minutes before got disconnected by sending an ack every 30 seconds, but after exactly 5 minutes I got disconnected with the same error. Did you were able to find a solution?

**Comment by 0xFlint** [comment]
Its not the APK, its server-side

**Comment by acalatrava** [comment]
I know it's server side, in fact I'm pretty sure this is a mess up from WhatsApp. This is only happening on new registrations when WhatsApp send the sample STATUS messages. In fact this is happening on a regular Android APK just downloaded from the Play Store with no modifications at all:
 - Download APK from Play Store
 - Inspect the traffic to WhatsApp server
 - Register a new number
 - You will receive the 6 PSA status notification
 - After 180 seconds the connection is dropped with the same error, and the client reconnect again and receive again the PSA status notification

As you can see this is happening on their standard app, both on iPhone and Android so this is why I'm pretty sure it's a mess up on their side. I just hope they will fix it soon but maybe they are not aware of it since the app reconnects and it continue to work AND since this is only happening to new registrations...

**Comment by 0xFlint** [comment]
It could be an intended change of behavior, although i doubt it due to the stream error which is a protocol error.

I think they are aware but its low priority due to the fact that it has no viewability from the user side except from annoyance overhead network usage( connect/disconnects and tons of notifications is sent back and forth)

**Comment by acalatrava** [comment]
Wow it seems they fixed it! Isn't it?
