### ISSUE TITLE
WhatsApp API Repo with Protocol 2.0 and 2.1

### ISSUE THREAD

**Issue by ben221199** [mgp25/Chat-API#2251]
Hello mgp25,

I know this repository is 'End of Support' (#2116), so that is why I created a new repository on my own account.

I know how registration works.
Thanks for solving my previous issue!!!

Before I can fully implement the new WhatsApp API, I have to know something more about protocol 2.0.
When this issue is solved, I can make my repository and future issues could be posted there.

I know that the protcol before 2.0 started with 'WA' and than two bytes indicating the version.
In protocol 2.0 it looks like they added a new header: 'ED' also followed by two bytes indicating a version.
WA stands for WhatsApp, but where stands ED for?

For me, it looks like this:

| Bytes | Explaination |
| --- | --- |
| 45 44 00 01 | ED 0.1 |
| 00 00 04 | Int24 length |
| 08 05 08 02 | 4 bytes (see length), but I don't know what they mean |
| 57 41 02 01 | WA 2.1 (the old known WhatsApp header)
| 00 00 FB | Int24 length |
| 12 F8 01 0A 20 8B ... | 251 bytes (see length); I think this data encrypted with the Noise Protocol |

So things I need to know, before I can take over your work, are:
 - What is ED? Why is it there? Was it also there in protocols before 2.0?
 - What are that 4 unknown bytes?
 - How does Noise Protocol work? Some things are explained here: https://github.com/mgp25/Chat-API/wiki/Authentication-Overview-(WA-2.0)

I hope you can help. When it's solved, maybe you don't have to look to this repo any more for ever.

**Comment by mgp25** [comment]
Well, I don't recommend you to bother doing this. The implementation of the new protocol is already done and working pretty good. The fact I haven't published the code is because this community is toxic. Most of the people here want this for commercial or spamming purposes.

I left the repository open so people could still access to the information. I have also started other repo where I wanted to write about the whole implementation and how it is done. Haven't found the motivation or time to start writing about it.

I don't know if I can trust you and if your purposes on this are okay, if so I wouldn't mind sharing all my code. But again, trusting to an unknown third party is not a good idea.

Hope you understand the situation

Regards

**Comment by ben221199** [comment]
I understand your problem. It isn't nice when people abuse your creation. I didn't have any plan to use it for spam.

So, for now, I think I have to invent it myself.

**Comment by ben221199** [comment]
@lisabrauns I think we have to invent it ourselfs. I'm trying to make documention on my own repository "WAPI".

**Comment by lisabrauns** [comment]
@ben221199  Yes, but after reading the code of whatsapp, I still can't understand the principle of it, so I want to see the implementation of others so that I can understand it myself. If you have any good articles, you can recommend it to me.

**Comment by ben221199** [comment]
Only change is the switch from RC4 to Noise.

**Comment by lisabrauns** [comment]
Do you have documentation or how to implement the code for me to learn? Such as logging in or syncing contacts

**Comment by ben221199** [comment]
I can only make documentation when I have a working script and to have a working script, I have to know how the Noise encryption works. Watch my repository, so you will stay tuned when there are updates.
