### ISSUE TITLE
"getMediaFile updated" commit issues

### ISSUE THREAD

**Issue by ludufre** [mgp25/Chat-API#733]
Hi!

After update to the last commit (getMediaFile updated) I get the error while sending a image or video:

```url
http://s4.gamevicio.com/images/capas/7/7721.jpg
```
``` dos
PHP Notice:  Undefined index: filesize in /var/www/ludufre/wpp/api/whatsprot.class.php on line 2425

Notice: Undefined index: filesize in /var/www/ludufre/wpp/api/whatsprot.class.php on line 2425
PHP Warning:  hash_file(/var/www/ludufre/wpp/api/wadata/media/WHAmiu3Q0): failed to open stream: No such file or directory in /var/www/ludufre/wpp/api/whatsprot.class.php on line 3673

Warning: hash_file(/var/www/ludufre/wpp/api/wadata/media/WHAmiu3Q0): failed to open stream: No such file or directory in /var/www/ludufre/wpp/api/whatsprot.class.php on line 3673
tx  <iq id="9" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="" type="image" size="6094"></media>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="9" type="error">
rx    <error code="400" text="bad-request"></error>
rx  </iq>
```

The issues consists in two parts:

1) `Undefined index: filesize`

The `$this->mediaFileInfo['filesize']` is compared with `$maxsizebytes` on line 2425. But the value of the firts variable is not set yet in the current context. Only on line 2532.
Solution: Replaced line 2418 `$filesize   = strlen($image);` with `$this->mediaFileInfo['filesize'] = strlen($image);`

2) The file is removed before send. So, I commented the line `unlink($this->mediaFileInfo['filepath']);` and solved.

I'm ok on this or I missed something?

P.s. I don't know how to suggest change directly in the code.

**Comment by albertgil1989** [comment]
Hello, I have a problem that took several days trying to solve and the truth I could not . so I turn to you.
I 'm from Venezuela and do not speak English .
 The problem is this , when I try to send a picture or media file system sends me this error:

root@Newfies:~/CCR/WhatsAPI-Official/src# php send.php
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="584167831698">dHl▒584167831698g▒▒5▒▒ؒKmfiBLmJ▒▒▒1432065370</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

▒*'od<E▒[73</challenge>

tx  <response>v▒!U▒[▒▒▒G▒▒z▒▒) ▒iȑɥ▒▒▒</response>

rx  <success t="1432065370" props="4" kind="free" status="active" creation="1429105201" expiration="1460641201">,M▒vZ▒▒▒▒V▒▒J4▒▒yHe</success>

tx  <presence name="test"></presence>

tx  <iq id="1" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="TzylaVCjkhtMcEFJBGOey0ZKo1s5aN1Pr9Oa7clTkCw=" type="image" size="162697"></media>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="584167831698@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" id="1" type="result">
rx    <media url="https://mmi110.whatsapp.net/u/JXt3ZXqVhIduwupyHALVIk4NuZQABRZiT44M1w/AqmQH3aKkbTqZDO8uQye6mjO7x0BlyaaakGZ_RCGySdA" ip="173.192.231.35"></media>
rx  </iq>

PHP Warning:  fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /root/CCR/WhatsAPI-Official/src/mediauploader.php on line 12
PHP Warning:  fsockopen(): Failed to enable crypto in /root/CCR/WhatsAPI-Official/src/mediauploader.php on line 12
PHP Warning:  fsockopen(): unable to connect to ssl://mmi110.whatsapp.net:443 (Unknown error) in /root/CCR/WhatsAPI-Official/src/mediauploader.php on line 12

please help me.

**Comment by ludufre** [comment]
First of all. Post changes between ```. Secondly, update your code to last commit.

**Comment by albertgil1989** [comment]
greetings and sorry my mistakes and my bad English . I have the latest version , the problem derive the update files .

**Comment by albertgil1989** [comment]
greetings and sorry my mistakes and my bad English . I have the latest version , the problem derive the update files .

**Comment by ludufre** [comment]
@albertgil1989 The problem should be the date and time of your system, because it is accusing the certificate has expired. Or the file you are sending is on an HTTPS server with expired certificate. Tell me the address of the image / picture begins with http:// or https://?

**Comment by albertgil1989** [comment]
https://s-media-cache-ak0.pinimg.com/originals/b4/c5/d0/b4c5d0dfdfcb109688ed6793f9d991f1.jpg

I'm using Debian 8 .
I've also tried with local images and does not work , I get error Same error. I will chek hour

**Comment by albertgil1989** [comment]
https://s-media-cache-ak0.pinimg.com/originals/b4/c5/d0/b4c5d0dfdfcb109688ed6793f9d991f1.jpg

I'm using Debian 8 .
I've also tried with local images and does not work , I get error Same
error. I will chek hour

2015-05-19 17:26 GMT-05:00 Luan Freitas <notifications@github.com>:

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/commit/cd6ccdb31c80c230e783b6903636f35b19305647

**Comment by albertgil1989** [comment]
mediauploader no is funtional with debian 8, the upgrade php is more
secur.5.4. PHP
5.6 upgrade has behavioral changes

The upgrade to Jessie includes an upgrade of PHP from 5.4 to 5.6. This may
affect any local PHP scripts and you are advised to check those scripts
before upgrading. Below are a selected subset of these issues:

   -

   To prevent man-in-the-middle attacks against encrypted transfers, client
   streams now verify peer certificates by default.

   As a result of this change, existing code using ssl:// or tls:// stream
   wrappers (e.g. file_get_contents(), fsockopen(), stream_socket_client())
   may no longer connect successfully without manually disabling peer
   verification via the stream context's "verify_peer" setting.

   For more information about this particular issue, please read this
   document <https://wiki.php.net/rfc/tls-peer-verification>.
   -

   PHP changes the handling of case-insensitivity in many cases:
   -

      All internal case insensitivity handling for class, function, and
      constant names is done according to ASCII rules. Current locale settings
      are ignored.
      -

      The keywords "self", "parent", and "static" are now always case
      insensitive.
      -

      The json_decode() function no longer accepts non-lowercase variants
      of "boolean" values.
      -

   The logo GUID functions (e.g. php_logo_guid()) have been removed.
   -

   It is no longer possible to overwrite keys in static scalar arrays.
   Please see PHP bug 66015 <https://bugs.php.net/bug.php?id=66015> for an
   example and more information about this particular issue.
   -

   The mcrypt_encrypt(), mcrypt_decrypt() and mcrypt_{MODE}() functions no
   longer accept keys or IVs with incorrect sizes. Furthermore an IV is now
   required if the used block cipher mode requires it.
   -

   For legal reasons, the JSON implementation bundled with PHP has been
   replaced with the version provided by the "jsonc" PECL module. Code that
   makes assumptions about the finer implementation details of the PHP JSON
   parser may need to be reviewed.
   -

   The "short_open_tag" setting is now disabled by default. Short tags
   ("<?" and "?>") are scheduled for removal in PHP7.

For more information or the full list of potential issues, please have a
look at upstream's list of backwards incompatible changes for PHP 5.5
<https://php.net/manual/en/migration55.incompatible.php> and 5.6
<https://php.net/manual/en/migration56.incompatible.php>.

2015-05-19 18:18 GMT-05:00 mgp25 <notifications@github.com>:
