### ISSUE TITLE
congrats every one api ver. changed

### ISSUE THREAD

**Issue by sadiqhirani** [mgp25/Chat-API#751]
hey all
today this fine morning when i started to test the code which i developed with the help of whatsapi/chat-api
i found that v2 stopped registrations and new devices
and then i manually checked v.whatsapp.net/v3/ url... and i found that new ver of api is being applied (means v2 not fully stopped but some features of v2 are stopped)

**Comment by mgp25** [comment]
False, registrations still works, and this issue makes really no sense.

You havent realized that the problem is that you havent updated your code to latest version or even WhatsApp have blocked your server.

As i said, what you have posted makes no sense and is not true, proof:

```
Array
(
    [in] => number
    [cc] => 34
w|?????] => ???kb\?
    [lg] => es
    [lc] => ES
    [sim_mcc] => 214
    [sim_mnc] => 000
    [method] => sms
    [token] => 1289f***c80c1***3350416***53a***
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)
```

Biggest facepalm ever!
