### ISSUE TITLE
<presence from="123" type="unsubscribe"> wrongly handled/unclear meaning

### ISSUE THREAD

**Issue by derpue** [mgp25/Chat-API#767]
I see in my logs the following messages FROM the server:
`rx  <presence from="123456@s.whatsapp.net" type="unsubscribe"></presence>`
The current implementation (https://github.com/mgp25/Chat-API/blob/master/src/whatsprot.class.php#L2841 onwards) will handle that case as `onPresenceUnAvailable`

Since i'm not perfectly sure what that means i won't provide a pull request right now.
Is it just the information that the other part has removed us from his contactlist and we won't get any presence updates anymore, or just the message from the server that we need to take action and unsubscribe ourselves because the other side removed us from his list.
But interestingly, i got this from the server repeatedly mixed with normal presence availables.

Note: This contact is a non synced contact (the other side initated the chat, thus this contact will be automatically presencesubscripted by the whatsapp server). 

@mgp25 Do you know what exactly that message stands for?

**Comment by mgp25** [comment]
@derpue i think you got that, because one of your number removed his whatsapp account, and thats a way your client knows that number isnt in whatsapp anymore, i think.

As far as i know unsubscribe is when an user has removed the account.

If you are blocked or the account has been removed you will receive a presence unavailable, also you will receive a notification:

```xml
rx  <presence from="***@s.whatsapp.net" type="unavailable" last="deny"></presence>
``` 

```xml
rx  <notification from="123@s.whatsapp.net" id="2916841052" type="contacts" t="1432855923">
rx    <update jid="123@s.whatsapp.net"></update>
rx  </notification>
```
